'use client';
import {useState,useEffect} from 'react';
import {Sparkles,Search,Star,Copy,Check,ArrowUpRight,ArrowRight,PenLine,Code2,BriefcaseBusiness,GraduationCap,Languages,Lightbulb,X,BookOpen,SlidersHorizontal} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
const categories=['全部','代码理解','调试排错','代码优化','测试验证','设计开发'];
const icons=[Code2,BookOpen,Lightbulb,SlidersHorizontal,Check,PenLine];
const prompts=[
{id:1,title:'代码解释助手',cat:'代码理解',desc:'从整体流程到关键细节，快速读懂陌生代码。',tags:['代码解读','新手友好'],prompt:'你是一位耐心的高级程序员。请解释下面代码的作用、输入输出、执行流程和关键语法。先概括整体逻辑，再解释重要部分，最后用一个小例子说明运行过程。区分代码实际行为与需要更多上下文才能判断的内容。\n\n编程语言：[语言]\n代码：\n[粘贴代码]'},
{id:2,title:'Bug 定位与修复',cat:'调试排错',desc:'结合报错与复现步骤，缩小问题范围并找到根因。',tags:['Bug修复','错误分析'],prompt:'请帮助我定位下面的问题。先结合错误信息和复现步骤分析可能原因，按可能性排序，给出验证方法。信息不足时先指出需要的最少信息。给出最小修复方案和验证步骤，不假设未提供的代码。\n\n语言与版本：[填写]\n预期行为：[填写]\n实际行为与报错：[填写]\n复现步骤及相关代码：[粘贴]'},
{id:3,title:'代码审查伙伴',cat:'代码优化',desc:'关注正确性与边界情况，给出有依据的改进建议。',tags:['Code Review','质量提升'],prompt:'你是一位代码审查工程师。请审查下面代码的正确性、错误处理、边界条件、安全性和可维护性。按严重程度列出问题，说明触发条件、影响、对应位置和最小修改建议。不要猜测未展示的实现，也不要为了提出建议而强行修改。\n\n项目背景：[填写]\n代码：\n[粘贴代码]'},
{id:4,title:'单元测试生成',cat:'测试验证',desc:'覆盖正常路径与异常边界，让测试真正验证行为。',tags:['单元测试','边界条件'],prompt:'请为下面代码编写单元测试，使用[语言与测试框架]。覆盖正常输入、边界值、无效输入和异常路径。先列出测试场景及预期结果，再给出可运行的测试代码。仅模拟真正的外部依赖，避免重复实现被测逻辑。\n\n函数规格：[填写]\n代码：\n[粘贴代码]'},
{id:5,title:'安全重构助手',cat:'代码优化',desc:'保留现有行为，逐步改善结构与可读性。',tags:['代码重构','可维护性'],prompt:'请重构以下代码，目标是[重构目标]。保持现有对外接口和可观察行为不变。先解释当前结构的问题，再提出小步骤重构方案，提供修改后的代码和回归验证建议。说明任何无法保证等价的变化，不引入无必要的依赖。\n\n代码及约束：\n[粘贴内容]'},
{id:6,title:'REST API 设计',cat:'设计开发',desc:'从业务需求出发，设计清晰一致的接口。',tags:['接口设计','后端开发'],prompt:'请根据以下业务需求设计 REST API。列出资源、端点、HTTP 方法、请求字段、响应结构与状态码。说明校验、权限、分页和错误处理方式，仅包含需求所需的功能。提供典型请求响应示例，并列出待确认问题。\n\n业务需求：[填写]\n技术约束：[填写]'},
{id:7,title:'性能瓶颈分析',cat:'代码优化',desc:'先测量再优化，找出真正值得改进的慢点。',tags:['性能优化','复杂度'],prompt:'请分析以下代码可能的性能瓶颈，解释时间与空间复杂度。区分有依据的问题与需要测量的假设，给出基准测试或性能剖析方法。建议优化时说明适用条件、代价及如何验证效果，不承诺未经测试的提升幅度。\n\n代码：[粘贴]\n数据规模与耗时：[填写]\n运行环境：[填写]'},
{id:8,title:'SQL 查询助手',cat:'设计开发',desc:'结合表结构写查询，并说明关联与聚合逻辑。',tags:['SQL','数据库'],prompt:'请根据提供的数据库表结构和业务问题编写 SQL，数据库类型为[类型及版本]。解释关联、过滤与聚合逻辑，处理空值和重复记录。给出只读查询及少量样例的预期结果。不要假设未提供的列或索引。\n\n表结构：[填写]\n业务问题：[填写]'},
{id:9,title:'正则表达式解析',cat:'代码理解',desc:'拆解匹配规则，用正反例说明适用边界。',tags:['正则表达式','文本处理'],prompt:'请解释下面的正则表达式。逐段说明含义，提供能匹配和不能匹配的示例，并指出贪婪匹配、边界和转义相关注意事项。以[语言或正则引擎]的行为为准，不确定的差异请明确说明。\n\n正则表达式：[填写]\n期望匹配的内容：[填写]'},
{id:10,title:'前端组件开发',cat:'设计开发',desc:'明确状态与交互，写出易维护的界面组件。',tags:['React','前端开发'],prompt:'请使用[框架及版本]实现以下组件需求。先梳理输入属性、状态和用户交互，再给出完整组件代码与最小使用示例。考虑键盘操作、可访问标签、空状态和错误状态。沿用提供的样式与组件约定，不添加额外功能。\n\n组件需求：[填写]\n项目约定：[填写]'},
{id:11,title:'报错日志解读',cat:'调试排错',desc:'提取关键错误线索，区分根因和连带报错。',tags:['日志分析','故障排查'],prompt:'请分析下面经过脱敏的报错日志。提取首个相关错误、调用链与环境线索，区分根因候选和连带错误。按优先级列出排查步骤，说明每一步验证什么以及不同结果的下一步。不要仅凭日志断言未经证实的根因。\n\n环境与最近变更：[填写]\n日志：\n[粘贴脱敏日志]'},
{id:12,title:'测试用例设计',cat:'测试验证',desc:'从需求设计可验收的场景，覆盖关键异常路径。',tags:['测试用例','功能验收'],prompt:'你是一位测试工程师。请根据以下功能需求设计测试用例，用表格列出场景、前置条件、操作步骤、预期结果和优先级。覆盖核心流程、边界输入、失败恢复与相关权限场景。明确需求歧义，不将假设写成已确认标准。\n\n功能需求：[填写]'}
];
type Prompt=typeof prompts[number];
export default function Home(){const [category,setCategory]=useState('全部'),[search,setSearch]=useState(''),[onlySaved,setOnlySaved]=useState(false),[favorites,setFavorites]=useState<number[]>([]),[active,setActive]=useState<Prompt|null>(null),[draft,setDraft]=useState(''),[status,setStatus]=useState(''),[copied,setCopied]=useState<number|null>(null),[sort,setSort]=useState('精选顺序'),[help,setHelp]=useState(false);
useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const controller=new AbortController();try{Promise.resolve(context.registerTool({name:'get_programming_prompt',title:'读取编程提示词',description:'根据模板编号读取本页编程提示词，不修改收藏或剪贴板。',inputSchema:{type:'object',properties:{id:{type:'integer',minimum:1,maximum:12}},required:['id'],additionalProperties:false},annotations:{readOnlyHint:true},execute(input:unknown){const id=(input as {id?:unknown})?.id;if(!Number.isInteger(id))throw new Error('需要整数模板编号');const p=prompts.find(p=>p.id===id);if(!p)throw new Error('模板不存在');return {id:p.id,title:p.title,prompt:p.prompt}}},{signal:controller.signal})).catch(()=>{});}catch{}return()=>controller.abort()},[]);useEffect(()=>{try{const value=JSON.parse(localStorage.getItem('prompt-demo-favorites')||'[]');if(Array.isArray(value))setFavorites(value.filter(v=>Number.isInteger(v)&&prompts.some(p=>p.id===v)))}catch{setStatus('本机收藏暂不可用，仍可浏览与复制。')}},[]);
const shown=prompts.filter(p=>(category==='全部'||p.cat===category)&&(!onlySaved||favorites.includes(p.id))&&`${p.title}${p.desc}${p.cat}${p.tags.join('')}${p.prompt}`.toLowerCase().includes(search.trim().toLowerCase())).sort((a,b)=>sort==='名称排序'?a.title.localeCompare(b.title,'zh-CN'):a.id-b.id);
function favorite(id:number){const next=favorites.includes(id)?favorites.filter(v=>v!==id):[...favorites,id];try{localStorage.setItem('prompt-demo-favorites',JSON.stringify(next));setFavorites(next)}catch{setStatus('收藏保存失败，请复制提示词自行保存。')}}
async function copy(p:Prompt,value=p.prompt){try{await navigator.clipboard.writeText(value);setCopied(p.id);setStatus('已复制提示词，粘贴到你常用的 AI 工具即可使用。')}catch{setActive(p);setDraft(value);setStatus('自动复制不可用，请在详情中选中文字手动复制。')}}
function open(p:Prompt){setActive(p);setDraft(p.prompt)}
return <><header className="header"><div className="header-inner"><a className="brand" href="#" onClick={()=>{setOnlySaved(false);setCategory('全部');setSearch('')}}><span className="brand-mark"><Sparkles size={21}/></span>CodePrompt<span className="brand-en">编程提示词</span></a><nav><button className={!onlySaved?'nav active':'nav'} onClick={()=>setOnlySaved(false)}>编程提示词</button><button className={onlySaved?'nav active':'nav'} onClick={()=>setOnlySaved(true)}>我的收藏<span>{favorites.length}</span></button><button className="nav guide" onClick={()=>setHelp(true)}>使用指南<ArrowUpRight size={13}/></button></nav><span className="demo">DEMO <span>0.1</span></span></div></header>
<main><section className="intro"><div className="intro-copy"><div className="eyebrow"><span/> 为开发者准备的提示词工具箱</div><h1>编程好帮手，<span>从一句好提示开始。</span></h1><p>读代码、修 Bug、写测试。找到场景，复制即用。</p></div><div className="intro-note"><Sparkles size={24}/><span>一个好问题<br/>是好答案的开始。</span></div></section>
<section className="explorer" aria-label="筛选提示词"><div className="search-line"><div className="search"><Search size={20}/><input aria-label="搜索提示词" placeholder="搜索编程场景，例如：Bug、React、SQL…" value={search} onChange={e=>setSearch(e.target.value)}/>{search?<button aria-label="清空搜索" onClick={()=>setSearch('')}><X size={17}/></button>:<span className="search-hint">搜索灵感</span>}</div><div className="library-count"><b>12</b><span>精选提示词</span></div></div><div className="categories">{categories.map((c,i)=>{const Icon=icons[i];return <button key={c} className={'category '+(category===c?'selected':'')} aria-pressed={category===c} onClick={()=>setCategory(c)}><Icon size={16}/>{c}{c==='全部'&&<small>12</small>}</button>})}</div></section>
<div className="results-head"><h2>{onlySaved?'我的收藏':category==='全部'?'精选编程提示词':category}<span>{shown.length} 个结果</span></h2><div className="sort"><SlidersHorizontal size={14}/><Select value={sort} onValueChange={v=>v&&setSort(v)}><SelectTrigger aria-label="排序方式"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="精选顺序">精选顺序</SelectItem><SelectItem value="名称排序">名称排序</SelectItem></SelectContent></Select></div></div>
<section className="cards" aria-label="提示词列表">{shown.map(p=>{const index=categories.indexOf(p.cat),Icon=icons[index];return <article className="card" key={p.id}><div className="card-top"><span className={'card-icon tone-'+index}><Icon size={20}/></span><span className="card-category">{p.cat}</span><button className={'star '+(favorites.includes(p.id)?'saved':'')} aria-label={(favorites.includes(p.id)?'取消收藏':'收藏')+p.title} aria-pressed={favorites.includes(p.id)} onClick={()=>favorite(p.id)}><Star size={18} fill={favorites.includes(p.id)?'currentColor':'none'}/></button></div><button className="card-title" onClick={()=>open(p)}>{p.title}<ArrowUpRight size={16}/></button><p className="description">{p.desc}</p><div className="tags">{p.tags.map(tag=><button key={tag} onClick={()=>{setSearch(tag);setCategory('全部')}}>#{tag}</button>)}</div><button className="excerpt" onClick={()=>open(p)} aria-label={'查看'+p.title+'完整提示词'}>{p.prompt}</button><div className="card-bottom"><button className="details" onClick={()=>open(p)}>查看详情<ArrowRight size={13}/></button><button className={'copy '+(copied===p.id?'copied':'')} onClick={()=>copy(p)}>{copied===p.id?<Check size={14}/>:<Copy size={14}/>} {copied===p.id?'已复制':'复制提示词'}</button></div></article>})}</section>
{!shown.length&&<div className="empty"><Search size={30}/><h2>{onlySaved?'这里还没有匹配的收藏':'没有找到匹配的提示词'}</h2><p>{onlySaved?'点击卡片右上角的星标，将好用的提示词留在这里。':'试试更短的关键词，或者换个分类。'}</p><button onClick={()=>{setOnlySaved(false);setSearch('');setCategory('全部')}}>浏览全部提示词<ArrowRight size={16}/></button></div>}
<footer><div><span className="footer-mark"><Sparkles size={14}/></span> CodePrompt<span>让每一次提问，更有方向。</span></div><p>演示版 · 收藏仅存当前浏览器 · 无 AI 调用费用</p></footer></main>
<Dialog open={active!==null} onOpenChange={v=>{if(!v)setActive(null)}}><DialogContent className="detail-dialog"><DialogHeader><span className="detail-category">{active?.cat}</span><DialogTitle>{active?.title}</DialogTitle><DialogDescription>{active?.desc}</DialogDescription></DialogHeader><label className="draft-label" htmlFor="prompt-draft">完整提示词 <span>替换方括号中的内容后使用</span></label><textarea id="prompt-draft" value={draft} onChange={e=>setDraft(e.target.value)} spellCheck={false}/><div className="dialog-actions"><button className="reset" onClick={()=>setDraft(active?.prompt||'')}>恢复原文</button><button className="copy" onClick={()=>active&&copy(active,draft)}><Copy size={15}/>复制当前内容</button></div></DialogContent></Dialog>
<Dialog open={help} onOpenChange={setHelp}><DialogContent><DialogHeader><DialogTitle>三步，让提示词为你所用</DialogTitle><DialogDescription>参考 AI Short 的分类与复制使用方式。</DialogDescription></DialogHeader><div className="help-steps"><p><b>01 · 找到场景</b>使用分类标签或关键词，找到适合的提示词。</p><p><b>02 · 填入内容</b>打开详情，将方括号占位内容替换成自己的需求。</p><p><b>03 · 复制使用</b>粘贴到你常用的 AI 工具，开始对话。</p><small>本 demo 提供 12 个独立编写的示例提示词。收藏保存在当前浏览器，没有登录或云端同步，也不直接调用 AI。</small></div></DialogContent></Dialog>
{status&&<div className="notice" role="status"><Check size={16}/>{status}<button aria-label="关闭提示" onClick={()=>setStatus('')}><X size={16}/></button></div>}</>}


