export const categoryNames: Record<string, Record<string, string>> = {
  zh: {
    programming: '编程开发',
    writing: '写作创作',
    office: '职场办公',
    marketing: '营销策划',
    study: '学习研究',
    language: '语言翻译',
    life: '生活出行',
    creative: '创意艺术',
    business: '商业分析',
    thinking: '思维表达',
  },
  en: {
    programming: 'Programming',
    writing: 'Writing',
    office: 'Office',
    marketing: 'Marketing',
    study: 'Learning & research',
    language: 'Languages',
    life: 'Life & travel',
    creative: 'Creative arts',
    business: 'Business',
    thinking: 'Thinking',
  },
  ja: {
    programming: 'プログラミング',
    writing: '執筆・文章',
    office: 'オフィス',
    marketing: 'マーケティング',
    study: '学習・研究',
    language: '言語・翻訳',
    life: '暮らし・旅行',
    creative: '創作・アート',
    business: 'ビジネス',
    thinking: '思考・表現',
  },
};
