export const ui = {
  zh: {
    library: '模板广场',
    favorites: '我的收藏',
    plans: '我的方案',
    care: '大字模式',
    title: '把想法变成好用的提示词',
    intro: '选择模板，写下需求，再复制到你使用的 AI 工具。',
    search: '搜索模板',
    all: '全部',
    use: '填写模板',
    empty: '暂无内容',
    loading: '正在加载…',
    retry: '重试',
    error: '操作失败，请重试。',
    save: '保存方案',
    saved: '方案已保存',
    update: '更新方案',
    copy: '复制提示词',
    copied: '已复制，可粘贴到 AI 工具使用。',
    copyFail: '请选中文字后手动复制。',
    download: '导出 TXT',
    close: '关闭',
    meta: '元提示词辅助',
    metaHelp:
      '加入角色、澄清问题、输出结构和自检规则，让 AI 更准确地理解你的需求。',
    preview: '提示词预览',
    previewHelp: '可以直接修改。修改表单会重新生成预览。',
    form: '填写需求',
    refresh: '换一组推荐',
    detect: '匹配需求中的词条',
    detected: '已将匹配的推荐词填入未锁定字段。',
    add: '添加',
    word: '自定义词条',
    lock: '锁定',
    unlock: '解锁',
    required: '请填写必填需求。',
    limit: '最多选择 5 个词条，每个不超过 40 字。',
    titleLabel: '方案名称',
    optional: '选填',
    requiredLabel: '必填',
    modeNote: '填写后复制使用；本站暂不直接生成代码、图片或视频。',
    preference: '语言',
    preserved: '语言已切换。你填写的内容和手动编辑的预览会保留，不会自动翻译。',
    reset: '按当前语言重新生成',
    resetHelp: '重新生成会替换手动编辑的预览。',
    source: '原创模板',
    oldPlans: '原有方案仍可打开和导出，旧模板暂保留原文。',
    noModel: '无需 API Key',
    favorited: '已更新收藏',
    sample: '填入示例',
    sampleHelp: '仅填充未锁定且为空的需求。',
    help: '使用说明',
    helpText:
      '1. 选择模板并填写需求。2. 点击推荐词，锁定不希望改变的字段。3. 开启元提示词辅助，加入澄清、结构和自检要求。4. 复制到你使用的 AI 工具，也可保存方案继续修改。语言切换不会翻译你自己的文字。',
    userData:
      '收藏和方案与当前浏览器关联；清除网站 Cookie 后可能无法找回，请及时导出。',
  },
  en: {
    library: 'Templates',
    favorites: 'Favorites',
    plans: 'My plans',
    care: 'Large text',
    title: 'Turn ideas into useful prompts',
    intro:
      'Choose a template, describe your goal, then copy it into your AI tool.',
    search: 'Search templates',
    all: 'All',
    use: 'Use template',
    empty: 'Nothing here yet',
    loading: 'Loading…',
    retry: 'Retry',
    error: 'Something went wrong. Please retry.',
    save: 'Save plan',
    saved: 'Plan saved',
    update: 'Update plan',
    copy: 'Copy prompt',
    copied: 'Copied. Paste into your AI tool.',
    copyFail: 'Select the text and copy it manually.',
    download: 'Export TXT',
    close: 'Close',
    meta: 'Meta-prompt guidance',
    metaHelp:
      'Add a role, clarification questions, output structure and review rules to make your request easier to follow.',
    preview: 'Prompt preview',
    previewHelp: 'Edit directly. Changing a field rebuilds the preview.',
    form: 'Describe your goal',
    refresh: 'Refresh suggestions',
    detect: 'Match keywords in your goal',
    detected: 'Matching suggestions were added to unlocked fields.',
    add: 'Add',
    word: 'Custom keyword',
    lock: 'Lock',
    unlock: 'Unlock',
    required: 'Fill in the required goal.',
    limit: 'Select up to 5 keywords, each at most 40 characters.',
    titleLabel: 'Plan name',
    optional: 'Optional',
    requiredLabel: 'Required',
    modeNote:
      'Copy the completed prompt into your AI tool. This site does not generate code, images or videos directly.',
    preference: 'Language',
    preserved:
      'Language changed. Your writing and manually edited preview are preserved, not translated.',
    reset: 'Rebuild in current language',
    resetHelp: 'Rebuilding replaces the manually edited preview.',
    source: 'Original template',
    oldPlans:
      'Existing plans can still be opened and exported. Older templates keep their original text.',
    noModel: 'No API key needed',
    favorited: 'Favorites updated',
    sample: 'Use example',
    sampleHelp: 'Fills the goal only if it is empty and unlocked.',
    help: 'How to use',
    helpText:
      '1. Choose a template and describe your goal. 2. Select suggestions and lock fields you want to keep. 3. Enable meta-prompt guidance for clarification, structure and review rules. 4. Copy into your AI tool, or save a plan to edit later. Language switching does not translate your own writing.',
    userData:
      'Favorites and plans belong to this browser. Clearing site cookies may remove access; export important plans.',
  },
  ja: {
    library: 'テンプレート',
    favorites: 'お気に入り',
    plans: '保存したプラン',
    care: '文字を大きく',
    title: 'アイデアを使いやすいプロンプトに',
    intro:
      'テンプレートを選び、要望を入力して、お使いのAIツールにコピーしましょう。',
    search: 'テンプレートを検索',
    all: 'すべて',
    use: 'このテンプレートを使う',
    empty: 'まだ内容がありません',
    loading: '読み込み中…',
    retry: '再試行',
    error: '操作に失敗しました。再試行してください。',
    save: 'プランを保存',
    saved: '保存しました',
    update: 'プランを更新',
    copy: 'プロンプトをコピー',
    copied: 'コピーしました。AIツールに貼り付けてください。',
    copyFail: 'テキストを選択して手動でコピーしてください。',
    download: 'TXTで保存',
    close: '閉じる',
    meta: 'メタプロンプト補助',
    metaHelp:
      '役割、確認質問、出力構成、自己チェックのルールを加え、AIに要望を伝えやすくします。',
    preview: 'プロンプトのプレビュー',
    previewHelp: '直接編集できます。フォームを変更すると再生成されます。',
    form: '要望を入力',
    refresh: '別の候補を表示',
    detect: '要望からキーワードを照合',
    detected: '一致した候補をロックされていない項目に入力しました。',
    add: '追加',
    word: '自由キーワード',
    lock: 'ロック',
    unlock: 'ロック解除',
    required: '必須の要望を入力してください。',
    limit: 'キーワードは5つまで、各40文字以内です。',
    titleLabel: 'プラン名',
    optional: '任意',
    requiredLabel: '必須',
    modeNote:
      '完成したプロンプトをAIツールにコピーしてください。このサイトではコード・画像・動画を直接生成しません。',
    preference: '言語',
    preserved:
      '言語を変更しました。入力した文章と手動編集したプレビューは保持され、自動翻訳されません。',
    reset: '現在の言語で再生成',
    resetHelp: '再生成すると手動編集したプレビューが置き換わります。',
    source: 'オリジナル',
    oldPlans:
      '既存プランは引き続き開いて保存できます。旧テンプレートは原文で表示します。',
    noModel: 'APIキー不要',
    favorited: 'お気に入りを更新しました',
    sample: '入力例を使う',
    sampleHelp: '要望が空欄でロックされていない場合のみ入力します。',
    help: '使い方',
    helpText:
      '1. テンプレートを選び、要望を入力します。2. 候補を選び、保持したい項目をロックします。3. メタプロンプト補助で確認・構成・チェックのルールを加えます。4. AIツールにコピーするか、プランを保存して後で編集します。言語の切り替えでは入力した文章は翻訳されません。',
    userData:
      'お気に入りとプランは現在のブラウザーに紐づきます。Cookieを消すとアクセスできなくなる場合があるため、必要な内容を書き出してください。',
  },
};
