"""Package 12 reviewed, self-contained adaptations of pinned GitHub Skills."""
import hashlib,json,pathlib,zipfile
root=pathlib.Path(__file__).resolve().parents[1]
sources=json.loads((root/'data/sources/skill-expansion-upstream/manifest.json').read_text())
# id, task mapping, names zh/en/ja, scope zh/en/ja, workflow, exclusions
rows=[
('wps-ppt-outline',['wps-slides'],['WPS 演示大纲','WPS presentation outline','WPSプレゼン構成'],['规划逐页内容、配图和时间；不直接生成演示文件。','Plan slide content, visuals and timing; no direct deck generation.','各ページの内容・図・時間を計画。ファイル生成は別機能。'],
 'Establish audience, purpose, available evidence and total speaking time. Organize a narrative suited to the actual presentation rather than imposing a fixed slide count. For each slide give a message title, concrete talking points, the supporting source or missing evidence, a proposed visual and speaking duration. Allocate time for opening, transitions and questions; reconcile the total. Distinguish a report, training and product pitch. Keep facts and requested terminology unchanged. Deliver a numbered slide table plus preparation checklist, not merely chapter headings.', ['直接生成PPT文件','generate pptx file','PPTXファイル生成']),
('wps-ppt-speaker-notes',['wps-slides'],['WPS 逐页演讲备注','WPS speaker notes','WPS発表者ノート'],['依据已有页面内容写讲稿、过渡和时间；无页面时先索取内容。','Write notes, transitions and timing from supplied slides.','提供されたスライドから原稿・つなぎ・時間を作る。'],
 'Use actual slide text or a supplied outline; never claim to have read an absent deck. Confirm audience, voice and total duration. For every supplied slide produce an opening or transition, spoken explanation that adds meaning rather than reading bullets, evidence cues, and a transition to the next slide. Mark pauses and optional audience questions. Check the sum of times and present estimates, not measured speech duration. Keep page IDs aligned to the original. Output notes ready to paste into WPS; write a file only if a suitable tool is available, and verify it before claiming completion.', ['重新设计全部页面','redesign every slide','全ページの再設計']),
('wps-data-clean',['wps-sheet'],['WPS 数据清洗','WPS data cleaning','WPSデータ整形'],['清理空格、重复和类型；保留原始数据并报告改动。','Clean whitespace, duplicates and types while preserving originals.','空白・重複・型を整え原本と変更記録を残す。'],
 'Inspect representative rows and establish column meanings, unique keys and locale before proposing changes. Produce a diagnosis with affected columns and examples. Define explicit whitespace, duplicate, missing-value, date and numeric rules; keep identifiers and leading zeros as text. Never guess a city from an ambiguous district, infer personal attributes, or silently convert unknown values. Work on a copy when file tools exist. Return a rule table, before/after examples, unresolved records, original and resulting row counts, and reconciliation checks. Without a workbook tool provide WPS steps or formulas and clearly label them unexecuted.', ['制作动画','make an animation','アニメ制作','透视表','pivot table','ピボット','公式','formula','数式']),
('wps-pivot',['office-focused-pivot'],['WPS 数据透视表','WPS pivot tables','WPSピボットテーブル'],['按问题配置行列、值、筛选与刷新核对。','Configure rows, columns, values, filters and refresh checks.','問いに合わせ行列・値・絞込・更新確認を設計。'],
 'Translate the question into grouping fields and a measure. Ask for column names, sample rows, data types and aggregation meaning. Give a field placement table for rows, columns, values and filters; specify sum, count, distinct count or weighted calculation carefully. Distinguish averaging rows from calculating a ratio of totals. Describe WPS creation and refresh steps subject to the actual version. Check blanks, duplicates, text numbers, date groups, grand totals and source range growth. A calculated static summary is not a refreshable native pivot table: state which output was produced. Provide a small expected-results example from supplied data.', ['宏自动化','macro automation','マクロ自動化']),
('wps-pdf-extract',['wps-pdf'],['PDF 文字与表格提取','PDF text and table extraction','PDF文字・表の抽出'],['提取可读文本与表格，标注页码、OCR疑点和布局损失。','Extract text and tables with page provenance and OCR uncertainty.','文字・表を抽出しページとOCR不確実性を記す。'],
 'Confirm requested pages, fields and output format. Determine whether the supplied PDF has selectable text, scanned images or mixed pages using available tools. Preserve page provenance, headings, table columns, units, footnotes and reading order. Flag merged-cell ambiguity and uncertain OCR instead of inventing missing characters or values. If OCR/file tools are unavailable, request pasted text or an accessible extract and do not claim extraction. Compare a sample of the output against original pages; check totals and row alignment. Deliver extracted content, a page/field uncertainty log and a concise verification checklist. Respect file access restrictions.', ['绕过密码','bypass password','パスワード回避']),
('wps-docx-writer',['wps-writing','office-focused-merge-docs'],['WPS 文档结构与排版','WPS document structure','WPS文書構造と書式'],['制作文档正文、标题层级、编号与排版方案。','Draft documents with heading hierarchy, numbering and layout.','本文・見出し階層・番号・レイアウトを整える。'],
 'Identify document type, audience, supplied facts and formatting requirements. Draft usable text while retaining names, dates and amounts; mark unknowns. Define heading levels, paragraph styles, list numbering, page breaks, table captions and cross-references. Prefer automatic fields for a table of contents and numbering; describe refresh checks. Preserve the user template rather than forcing a preset font or official format. Without editing tools return complete content and WPS steps; with tools save a separate output and inspect page layout for clipped text, broken tables and blank pages. Do not promise an editable file without producing one.', ['自动签署','automatically sign','自動署名','公式','formula','数式','透视表','pivot table','ピボット']),
('test-driven-development',['testing-unit','testing-focused-boundaries'],['测试驱动开发','Test-driven development','テスト駆動開発'],['围绕可观察行为建立失败用例，再做最小修复。','Start with a behavioral failing test, then a minimal implementation.','観測可能な振る舞いの失敗テストから最小実装へ。'],
 'Use the project test framework and requested behavior. Design the smallest regression case with input, expected result and a meaningful assertion. Run it before the change when execution is available and verify that failure reflects the missing behavior, not broken setup. Implement the smallest relevant fix, run the targeted test, then affected regressions. Refactor while keeping tests passing. For date/money boundaries state units, rounding, timezone and edge cases. Preserve existing user code; do not delete an implementation to enforce a ritual. Report commands, exit results and untested limitations. Without execution provide test code and expected failures, never fabricated results.', ['只改文案','copy-only change','文章だけの変更']),
('receiving-code-review',['review','git-review'],['代码审查意见核对','Code review feedback','レビュー指摘の検証'],['核对已有审查意见的证据，再决定修复；不自动接受建议。','Verify supplied review feedback before applying changes.','既存の指摘を検証してから修正する。'],
 'When feedback is supplied, restate each requested change and locate the relevant code and behavior. Distinguish confirmed defects, preferences, unsupported assumptions and unclear requests. Evaluate compatibility and existing callers before modifying code. For each actionable item provide evidence, impact and the smallest change plus a regression case. Explain technical disagreement concretely; clarify only blocked items while continuing independent checks. Without review feedback, ask for it rather than inventing reviewer comments. Do not submit replies, merge or change repository permissions automatically. Report implemented versus proposed changes separately.', ['自动合并','automatic merge','自動マージ']),
('verification-before-completion',['testing-journey','testing-report'],['交付前验证','Delivery verification','完了前の検証'],['按验收条件核对命令、结果与未覆盖项。','Map acceptance criteria to checks, results and coverage gaps.','受入条件と確認結果・未検証項目を対応づける。'],
 'List concrete completion claims and the evidence each requires: reproduction, unit test, integration behavior, build or visible output. Select checks proportional to the change and run them when authorized tools exist. Read exit codes and full relevant results; an old pass or a build alone does not establish current functional correctness. For a reported bug compare the original trigger and corrected result. Map each acceptance criterion to a check and state unresolved gaps. When commands cannot run, provide reproducible steps and clearly mark not executed. Avoid repeated unrelated testing or claiming completion solely from another agent report.', ['保证零缺陷','guarantee zero defects','無欠陥保証']),
('prompt-images',['image','photo-focused-restore','photo-focused-background','photo-focused-series','character-turnaround','character-expression','character-focused-wardrobe'],['图片描述与局部修改','Image prompts and local edits','画像プロンプトと局所編集'],['明确主体、构图与保留项；适合图片生成和局部修复描述。','Describe subject, composition and preserved elements for generation or local edits.','主体・構図・保持条件を明確にし生成や部分修正を指示。'],
 'Choose generation or editing from the actual request. Describe subjects by identity and position, materials, spatial relationships, lighting, palette, aspect ratio and intended use in natural language. For editing list preserve/change/do-not-change; request the reference if absent. For old photos describe visible damage separately from desired repairs and do not reconstruct unknown facial details as historical truth. For a character keep identity, face and body distinct from changeable clothing or pose. Provide a copyable prompt plus an inspection checklist. Include mask, negative-prompt or reference settings only if the chosen tool supports them. No Replicate API or companion Skill is required for this adaptation; verify current tool limits rather than quoting preset model claims.', ['生成视频','generate video','動画生成']),
('prompt-videos',['clip','production-focused-loop','production-focused-repair'],['视频动作与镜头提示词','Video action and camera prompts','動画の動作・カメラ指示'],['描述单镜头动作、起止状态与运镜；不代替多镜头剪辑。','Specify single-shot action, start/end state and camera movement.','単一カットの動作・開始終了・カメラを指定。'],
 'Establish the shot purpose, available reference image, desired duration and output format. Describe subject, context, one main action, style, camera, framing and atmosphere without conflicting movements. Separate fixed appearance/background from changes over time. Specify start, intermediate motion and final state; for loops reconcile pose, camera and lighting at the seam. For defect repair preserve approved elements and change only the visible defect. Produce a ready-to-copy prompt and continuity checks; propose settings only after checking the target tool. Do not infer that a duration, resolution, negative prompt or audio feature is supported. This adaptation does not call Replicate or bundle media generation.', ['静态海报','static poster','静止ポスター']),
('storyboard-workflow',['storyboard','production-bible','production-shots','production-continuity','character-focused-grid','production-focused-vertical'],['分镜与角色场景一致性','Storyboards and continuity','絵コンテと連続性'],['组织角色设定、近中远景、逐镜提示词与连续性检查。','Organize character bibles, shot sizes, prompts and continuity checks.','キャラ設定・近中遠景・カット別指示・連続性を整理。'],
 'Use supplied story facts, characters and reference images; missing images remain requested inputs. Build a compact character/style/location bible with fixed and changeable traits. For each shot give ID, story purpose, framing (close/medium/wide with visible body or scene coverage), angle, action, props, lighting, duration and transition. For a nine-panel request number a 3x3 grid and give a distinct purpose for every panel without mechanically cycling shot sizes. Keep geography, screen direction, wardrobe and prop state consistent. Separate production notes from self-contained image prompts. For revisions output Preserve, Change, Do-not-change and target-frame description. In chat return tables; create tracking files only when available tools and the user task require them. Never claim images were generated from text alone.', ['仅表格公式','spreadsheet formulas only','表計算数式のみ']),
]
catalog_path=root/'data/studio/skills.json';catalog=json.loads(catalog_path.read_text(encoding='utf-8'))
fit_path=root/'data/studio/skill-fit.json';fit=json.loads(fit_path.read_text(encoding='utf-8'))
for id,tasks,labels,scopes,workflow,excluded in rows:
    src=next(s for s in sources if s['id']==id)
    folder=root/'data/sources/skills'/id;folder.mkdir(parents=True,exist_ok=True)
    license_data=(root/'data/sources/skill-expansion-upstream'/id/'LICENSE').read_bytes()
    assert (b'Apache License' if src['license']=='Apache-2.0' else b'MIT License') in license_data
    (folder/'LICENSE').write_bytes(license_data)
    body=f"---\nname: {id}\ndescription: {scopes[1]}\nlicense: {src['license']}\ncompatibility: Self-contained instruction-only adaptation; no scripts, API keys or companion Skills required.\n---\n\n# {labels[1]}\n\nAdapted by AI Made Easy from [{src['repository']}]({src['source']}) at commit {src['commit']}. Changes: narrowed task scope, removed executable examples and external dependencies, added capability checks and factual-preservation rules. Original license retained.\n\n## Workflow\n\n{workflow}\n\n## Output and tool boundary\n\nUse the requested Chinese, English or Japanese response language. Preserve the user's literal facts and constraints. Ask only for missing details that change the deliverable. This package supplies instructions, not a model or runtime. Do not install tools, send private files, publish, or incur costs merely because this document mentions a workflow. If tools are absent, deliver the prompt, text or test plan and identify remaining steps. Distinguish observed results from expectations.\n"
    (folder/'SKILL.md').write_text(body,encoding='utf-8',newline='\n')
    usage={
      'zh':f'无脚本适配版。{scopes[0]} 解压后将文件夹导入支持 SKILL.md 的 AI 工具；普通聊天可粘贴 SKILL.md 与生成的提示词，并指定中文回答。没有模型、API Key 或软件安装。实际编辑文件、测试代码、生成图片视频需要目标 AI 的相应工具；无法执行时只输出内容和步骤，不能声称已完成。',
      'en':f'Instruction-only adaptation. {scopes[1]} Extract the folder into a tool supporting SKILL.md, or paste the document and generated prompt into chat. Request English output. No model, API key or installer is included. Editing files, running code and generating media require tools in the target AI; without them return content and steps without claiming execution.',
      'ja':f'スクリプト不要の調整版。{scopes[2]} 展開したフォルダーをSKILL.md対応ツールに導入するか、文書とプロンプトをチャットへ貼り付け、日本語を指定します。モデル・APIキー・インストーラーはありません。ファイル編集・実行・媒体生成は対象AIの機能が必要で、未実行なら内容と手順だけを示します。'}
    for locale in usage:(folder/f'USAGE.{locale}.md').write_text(f'# {labels[["zh","en","ja"].index(locale)]}\n\n{usage[locale]}\n\nSource: {src["source"]}\nLicense: {src["license"]}\n',encoding='utf-8',newline='\n')
    entry={**src,'tasks':tasks,'labels':dict(zip(['zh','en','ja'],labels)),'language':'en','edition':'adapted-documentation','review':'entrypoint-and-license-reviewed; external-ai-runtime-not-tested','usage':usage}
    entry['files']=[{'path':p.name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in sorted(folder.iterdir()) if p.is_file() and p.name!='manifest.json']
    (folder/'manifest.json').write_text(json.dumps(entry,ensure_ascii=False,indent=2)+'\n',encoding='utf-8',newline='\n')
    archive=root/'public/downloads/skills'/f'{id}-{src["commit"][:12]}-ame1.zip'
    with zipfile.ZipFile(archive,'w',zipfile.ZIP_DEFLATED) as z:
      for p in sorted(folder.iterdir()):
        info=zipfile.ZipInfo(id+'/'+p.name,(2026,9,15,0,0,0));info.compress_type=zipfile.ZIP_DEFLATED;z.writestr(info,p.read_bytes())
    entry.update(download='/downloads/skills/'+archive.name,sha256=hashlib.sha256(archive.read_bytes()).hexdigest(),bytes=archive.stat().st_size)
    catalog=[s for s in catalog if s['id']!=id]+[entry]
    fit[id]={'scope':dict(zip(['zh','en','ja'],scopes)),'exclude':excluded,'additionalTasks':[]}
catalog_path.write_text(json.dumps(catalog,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
fit_path.write_text(json.dumps(fit,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print('Packaged',len(rows),'new Skills;',len(catalog),'total')
