"""Original, task-specific briefs and self-contained instruction Skills. No upstream code is executed."""
import json,pathlib,hashlib,zipfile
root=pathlib.Path(__file__).resolve().parents[1]
def read(p): return json.loads((root/p).read_text(encoding='utf-8'))
def save(p,x): (root/p).write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
def tri(values): return dict(zip(('zh','en','ja'),values))
# Each row has its own deliverable, question and realistic input, not a generic role prompt.
rows=[
('programming-state-bug','programming',('状态更新与旧数据覆盖','Stale state and race conditions','古い状態による上書き'),('搜索结果被旧请求覆盖；保留最后一次输入。','Old search responses overwrite the latest result; preserve the last query.','古い検索結果が最新の結果を上書きする。最後の入力を優先したい。'),('提供触发步骤、状态相关代码，以及你期望保留哪个结果。','Share reproduction steps, state code and which result should win.','再現手順、状態管理コード、優先したい結果を教えてください。'),('画出请求和状态更新的先后顺序，确认闭包、取消和返回顺序。交付最小修复，覆盖慢请求晚到、切换对象和卸载场景；不要靠延时掩盖竞态。','Trace request and state-update order, closures, cancellation and response order. Deliver the smallest fix and tests for late responses, object switches and unmounting. Do not mask races with delays.','要求と状態更新の順序・クロージャ・取消を整理。遅い応答、対象切替、アンマウントの最小修正とテストを出し、待ち時間で隠さない。')),
('programming-legacy-change','programming',('安全修改旧项目','Change an existing codebase','既存コードを安全に変更'),('给旧网站增加筛选，但不能改变已有分页和链接。','Add filters to an existing site without breaking pagination or links.','既存サイトに絞込を追加し、ページ送りとリンクを維持したい。'),('提供相关文件、运行方式和必须保持不变的行为。','Share relevant files, run instructions and behavior that must stay unchanged.','関連ファイル、起動方法、保持すべき動作を教えてください。'),('先定位入口、调用方与数据流，列出本次改动范围。沿用现有依赖和约定，交付按文件说明的补丁、回归用例和回滚步骤。未见到的文件不要编造路径或接口。','Locate entrypoints, callers and data flow. Define scope, retain existing dependencies and conventions, and deliver file-specific patches, regression cases and rollback steps. Do not invent unseen files or APIs.','入口・呼出元・データ経路と変更範囲を確認。既存依存・規約に沿うファイル別修正、回帰確認、戻し方を示し、未確認のAPIやパスは作らない。')),
('office-print-layout','office',('WPS 打印分页与版式','WPS printing and pagination','WPSの印刷・改ページ'),('WPS 表格打印时右侧列被截断，希望一页宽、多页高。','WPS prints with the right columns cut off; fit one page wide and several tall.','WPSの印刷で右側の列が切れる。横は1ページ、縦は複数ページにしたい。'),('使用 WPS 文字还是表格？纸张、页边距和重复标题有什么要求？','WPS Writer or Spreadsheet? What paper, margins and repeated headers do you need?','WPS WriterかSpreadsheetか、用紙・余白・繰返し見出しの条件を教えてください。'),('先区分文字段落分页与表格缩放。给打印区域、纸张方向、宽高缩放、重复标题与预览核对步骤。避免无限缩小字号；版式冲突时给分表方案。菜单名称以实际版本为准。','Distinguish document pagination from spreadsheet scaling. Specify print area, orientation, width/height scaling, repeated headers and preview checks. Avoid unreadable shrinking; split tables if needed. Verify menu names in the installed version.','文書の改ページと表の縮尺を区別。印刷範囲、向き、幅高さ、繰返し見出しとプレビュー確認を示す。文字を極端に縮めず必要なら表を分割。メニュー名は版で確認。')),
('office-formula-locale','office',('公式版本与地区兼容','Formula version and locale compatibility','数式の版・地域互換'),('同一份公式在另一台 WPS 上报错，可能是函数版本或分隔符。','A formula fails on another WPS installation; check function version and separators.','別のWPSで同じ数式が動かない。関数の版や区切りを確認したい。'),('提供原公式、两端软件版本、报错文字和几行脱敏样例。','Provide the formula, both versions, exact error and a few anonymized rows.','元の数式、両端の版、エラー文、匿名化した数行を教えてください。'),('分别排查函数支持、逗号/分号、日期解析、文本数字与动态数组。不直接替换全部分隔符。给原版本可用公式与兼容替代，并用空值、重复值和边界日期校验。','Check function support, comma/semicolon separators, date parsing, text numbers and dynamic arrays separately. Do not globally replace separators. Provide a version-specific formula and fallback tested against blanks, duplicates and date boundaries.','関数対応、区切り、日付解析、文字列数値、動的配列を別々に確認。一括置換せず版別の数式と代替を出し、空白・重複・日付境界で検証。')),
('paper-evidence-matrix','paper',('论文论点与证据对应','Map paper claims to evidence','論文の主張と根拠の対応'),('把我上传的五篇文献对应到综述的三个论点。','Map five supplied papers to three claims in my literature review.','提供した5論文をレビューの3つの主張に対応させたい。'),('提供文献内容或可核对的摘录，以及三个论点。','Provide source text or verifiable excerpts and the three claims.','原資料または確認できる抜粋と、対象の主張を提示してください。'),('交付论点—来源—具体页码/段落—支持程度—局限矩阵。区分直接证据、间接推断和反证；无法访问原文标为待核。只用已给或已查证的文献，不编造 DOI、数据与页码。','Deliver a claim/source/page-or-section/support/limitations matrix. Separate direct evidence, inference and counterevidence; mark unavailable originals as unverified. Use only supplied or verified sources and never invent DOI, data or pages.','主張・出典・頁/節・支持度・限界の表を作る。直接証拠・推論・反証を区別し未読原文は未確認とする。DOI・数値・頁は捏造しない。')),
('paper-revision-response','paper',('从修改记录生成返修回复','Reviewer response from actual revisions','実修正に基づく査読回答'),('根据审稿意见和我已修改的段落，写返修信。','Draft a response letter from reviewer comments and my revised passages.','査読コメントと修正済み段落から回答書を作りたい。'),('提供审稿意见原文、实际修改，以及不采纳某条意见的理由。','Supply exact comments, actual changes and reasons for declining any suggestion.','コメント原文、実施した修正、不採用にする理由を提示してください。'),('保持每条意见原编号，依次写回应、实际改动和位置。未完成的实验或分析标为待做；不同意时用证据解释，保持礼貌。不声称已经做了未提供的改动。','Preserve comment numbering. For each give response, actual change and location. Mark unfinished analysis as pending; respectfully support disagreements with evidence. Never claim changes or experiments that were not performed.','元の番号を保ち、回答・実変更・位置を対応させる。未実施の実験は未実施と明記し、不同意は根拠を示す。実施していない変更を完了扱いしない。')),
('copy-channel-variants','copy',('同一内容分平台改写','Adapt copy for several channels','媒体別の文案調整'),('同一款产品分别写公众号介绍、小红书笔记和短视频口播。','Adapt one product brief into an article, a social post and spoken video copy.','同じ商品説明を記事、SNS投稿、動画ナレーションにしたい。'),('提供产品真实信息、受众、发布平台和不能变的价格或承诺。','Provide verified product facts, audience, channels and fixed prices or promises.','商品事実、読者、媒体、変更できない価格・約束を教えてください。'),('先固定事实表，再分别按平台阅读方式写完整正文、标题和行动指引。口播按呼吸断句，长文组织信息层级；不靠堆标签区分版本，不添加功效、优惠或虚假评价。','Lock a fact sheet, then write complete copy, titles and calls to action for each channel. Use speakable phrasing for narration and structured detail for articles. Do not distinguish versions merely with tags or invent benefits, offers or testimonials.','事実表を固定し、媒体ごとに見出し・本文・行動案内を作る。口播は読みやすい区切り、記事は情報階層を調整。架空の効能・値引き・評価を加えない。')),
('copy-specific-rewrite','copy',('保留事实的具体化改写','Make copy concrete without changing facts','事実を保持した具体的な推敲'),('这段介绍太空泛，希望说清楚给谁用、解决什么问题。','This introduction is vague; clarify who it serves and what it solves.','説明が抽象的なので、対象者と解決する問題を明確にしたい。'),('提供原文、真实例子或数据，以及希望保留的语气。','Provide the original, real examples or data and the desired tone.','原文、実例・数値、保持したい語調を提示してください。'),('标记空泛词对应的缺失信息，只根据已有事实改写完整正文。必要信息用少量明确待填项，不编造案例或百分比。另列关键修改及理由，避免把所有文案改成同一种风格。','Identify missing specifics behind vague claims. Rewrite the complete text using available facts; use a few explicit placeholders for essentials rather than invented cases or percentages. Explain major edits and retain the intended voice.','曖昧な表現に不足する情報を示し、既知の事実で全文を推敲。必要項目だけ未記入とし、事例や率を創作しない。主要変更理由と元の語調を保持。')),
('editing-dialogue-sync','editing',('视频对白与字幕时间对齐','Align dialogue and subtitle timing','台詞と字幕タイミング'),('两个人轮流说话，字幕需要不遮脸，不能提前泄露后一句。','Two speakers alternate; subtitles must avoid faces and not reveal the next line early.','二人が交互に話す。顔を隠さず、次の台詞を先に見せない字幕にしたい。'),('提供台词和已有时间码；是否需要双语、说话人标签？','Provide dialogue and available timestamps. Need bilingual text or speaker labels?','台詞と既存の時刻、二言語や話者表示の要否を教えてください。'),('按说话人和语义分段，输出起止时间、字幕、位置建议。无音频或时间码只能给待校准草稿，不假装已听取。检查相邻时间不重叠、无负时长，保留语气并列人工回听点。','Segment by speaker and meaning. Deliver start/end times, text and placement. Without audio/timestamps, label timing as a draft, never claim listening. Check overlap, positive durations and manual listening points while preserving tone.','話者と意味で区切り、開始終了時刻・字幕・位置を出す。音声や時刻がなければ仮案と明記し聴取済みにしない。重なり・正の時間・試聴確認点を点検。')),
('production-episode-handoff','production',('连续剧集交接与版本包','Series episode handoff','連続エピソードの引継ぎ'),('第三集接第二集结尾，角色衣服不能变，场景从门外进屋。','Episode three continues episode two: same clothes, moving from outside into the room.','第2話末から第3話へ。同じ服で玄関外から室内へ移動する。'),('提供上一集末镜头、固定人物设定和这集必须发生的事件。','Provide the previous ending, fixed character sheet and required events.','前話の末カット、固定人物設定、今回必要な出来事を教えてください。'),('分开固定设定和本集变量，交付集次摘要、场次、镜头表与素材清单。每镜写景别、动作、首尾状态、参考图和保留项；承接上集位置/道具/服饰。给已批准版本号与待核项，禁止静默覆盖旧镜头。','Separate canon from episode variables. Deliver synopsis, scenes, shots and assets. Each shot specifies framing, action, start/end states, references and invariants. Carry position/props/clothes across episodes; record approved versions and open checks without silently overwriting shots.','固定設定と各話変数を分離。概要・場面・カット・素材一覧を作り、景別・動作・首尾状態・参照・保持項目を記す。前話の位置・小物・服を継承し、承認版と未確認点を残す。')),
('photo-product-local-edit','photo',('商品图局部修改验收','Product image edit acceptance','商品画像の局所修正確認'),('只把瓶子后面的背景换成浅灰，商标和瓶身比例保持原样。','Replace only the bottle background with light gray; keep the logo and proportions.','瓶の背景だけ薄灰にし、ロゴと瓶の比率は保持したい。'),('提供原图、修改区域和不可改变的产品细节。','Supply the original, edit region and immutable product details.','原画像、変更領域、変えてはいけない商品細部を指定してください。'),('先列修改区域和保护区域，再写可复制的编辑指令。验收逐项对照商标、轮廓、颜色、尺寸比例、反光与接地阴影。没有图像查看能力时提供人工对照清单，不声称像素一致。','Define edited/protected regions, then produce an executable edit brief. Check logo, silhouette, color, proportions, reflections and contact shadow. Without image inspection, provide a human comparison checklist rather than claiming pixel identity.','変更領域と保護領域を分け、編集用指示を作る。ロゴ・輪郭・色・比率・反射・接地影を照合。画像確認機能がなければ目視一覧を出し、画素一致を断言しない。')),
('testing-acceptance-cases','testing',('把需求变成验收用例','Turn requirements into acceptance tests','要件から受入テストを作成'),('登录、保存、下载需要测试正常和异常流程，避免只测按钮能点。','Test login, saving and downloading across normal and failure flows, beyond button clicks.','ログイン・保存・ダウンロードの正常と失敗を、クリック可否だけでなく確認したい。'),('提供真实用户流程、权限角色、预期结果和测试环境。','Provide real flows, roles, expected results and test environment.','利用手順、権限、期待結果、テスト環境を提示してください。'),('逐项给前置条件、输入、操作、可观察结果和清理步骤。覆盖身份隔离、重试重复、断网、空数据、错误输入及恢复；区分自动化可验证项与需要人工判断项，不使用生产用户数据。','For each case specify preconditions, input, actions, observable outcome and cleanup. Cover identity isolation, repeated retries, offline behavior, empties, invalid input and recovery. Separate automated checks from human judgments and avoid production user data.','前提・入力・操作・観測結果・後片付けを明示。権限分離、再試行、オフライン、空値、不正値、復旧を含め、自動確認と人の判断を分け、本番利用者データは使わない。')),
]
tasks=read('data/studio/deep-tasks.json')
ids={r[0] for r in rows};tasks=[t for t in tasks if t['id'] not in ids]
for id,group,labels,examples,questions,guidance in rows:
 tasks.append(dict(id=id,group=group,labels=tri(labels),terms=list(labels)+[x.split('；')[0] for x in examples],guidance=tri(guidance),examples=tri(examples),questions=tri(questions),sourceReferences=[],editorialStatus='original-task-brief'))
save('data/studio/deep-tasks.json',tasks)
for locale in ('zh','en','ja'):
 for directory in ('','additional/','practical/','domain/'):
  path='data/studio/'+directory+locale+'.json';items=read(path)
  for template in items:
   group=template['id'][7:] if template['id'].startswith('studio-') else {'custom-office':'office','custom-paper-writing':'paper','custom-copy':'copy','custom-programming':'programming'}.get(template['id'])
   field=next((f for f in template['fields'] if f['key']=='task'),None)
   if field:
    for task in tasks:
     if task['id'] in ids and task['group']==group and task['labels'][locale] not in field['options']: field['options'].append(task['labels'][locale])
  save(path,items)
skills=read('data/studio/skills.json');fit=read('data/studio/skill-fit.json')
packages=[('ame-series-handoff',('连续视频项目交接','Series project handoff','連続動画の引継ぎ'),['production-episode-handoff','edit-video-continuity'],'Use for episode continuity and explicit shot handoffs, not for generating actual video files.', '''Ask for the last approved frame description, character/costume sheet, episode objective, target software and available references. If already supplied, do not ask again.
Separate immutable canon from episode-specific changes. Assign episode/scene/shot IDs. For each shot write duration preference, framing, subject action, camera motion, start state, end state, reference assets and invariants.
When revising, preserve approved shots and record before/after, reason and affected downstream shots. Suggest changes to downstream shots for confirmation rather than silently rewriting them.
Deliver: episode outline, shot table, one copyable production prompt per shot, reference checklist, handoff notes and unresolved continuity checks. Keep software settings separate from prompt text. Without actual visual inspection, describe continuity checks as textual/manual; never certify facial identity from descriptions alone.
Acceptance: adjacent end/start states connect; props and costumes persist unless an intentional change is recorded; every reference can be identified; no invented source images or model feature claims.'''),
('ame-image-edit-brief',('图片修改与保留清单','Image edit and preservation brief','画像編集・保持条件'),['photo-product-local-edit','edit-image-background','edit-image-object','edit-image-light','edit-image-text'],'Use for narrowly scoped edits to an existing image with explicit preserved elements.', '''Confirm original image availability, desired edit region, target software, intended use and non-negotiable details. Do not claim an image is uploaded unless accessible.
Create two lists: change and preserve. Clarify conflicts, such as changing a pose while demanding pixel-identical anatomy. Ask only essential unresolved questions.
Describe the desired final appearance of the region, perspective, light direction, edge blending and contact shadows. For text, quote exact characters and discuss manual typesetting when precision is required.
Deliver one concise edit prompt, a separate masking/reference checklist and acceptance checks for the protected subject, logo, proportions and untouched regions. Provide a targeted follow-up correction for a failed attempt rather than restarting every instruction.
Do not invent recovered details or promise pixel identity. If you cannot view images, label the acceptance list as a manual comparison plan. No image-generation engine is bundled.'''),
('ame-evidence-writing',('论文证据与返修整理','Evidence and revision writing','論文根拠・査読回答'),['paper-evidence-matrix','paper-revision-response'],'Use to map supplied paper claims to sources and draft traceable reviewer responses.', '''Determine whether the user needs a claim-evidence matrix or reviewer-response letter. Request relevant source excerpts and actual changes only if missing.
For evidence mapping, list claim, exact source, page/section if known, what the source supports, what it does not establish, and contrary findings. Clearly distinguish quotations, paraphrase and inference.
For responses, preserve reviewer numbering and quote supplied comments accurately. Map each response to a performed change and location. Label planned analysis as pending, never completed.
Deliver usable prose in the requested language followed by unresolved evidence checks. Retain technical definitions and hedging. Do not fabricate data, references, identifiers, pagination, experiments or journal requirements. Without access to originals, mark verification pending.
Acceptance: every factual claim has supplied/verified support or an explicit unresolved marker; every claimed revision exists in the supplied draft.'''),
('ame-acceptance-checklist',('网站功能验收','Website acceptance checks','ウェブ機能の受入確認'),['testing-acceptance-cases','programming-legacy-change'],'Use to convert concrete user journeys into testable acceptance cases; not a broad security certification.', '''Obtain user journeys, roles, expected outcomes and the permitted test environment. Inspect existing conventions if repository access exists.
Write cases with preconditions, anonymized inputs, observable outputs and cleanup. Cover a normal path and material failures: ownership isolation, duplicate retry, stale write, network interruption, empty state and invalid input.
Verify outcomes such as downloaded file integrity or persistence after reload, not merely that controls can be clicked. Do not mutate production customer data. If execution is unavailable, label cases as proposed rather than passed.
Deliver a concise pass/fail/not-run matrix with evidence, reproduction steps, prioritized fixes and remaining limitations. After fixes, rerun affected cases. Keep visual judgment separate from deterministic code checks.
No browser driver, credentials or test runtime is included. Use tools actually provided by the host and do not invent execution logs.''')]
for id,labels,taskids,description,body in packages:
 folder=root/'data/sources/skills'/id;folder.mkdir(parents=True,exist_ok=True)
 skilltext=f'---\nname: {id}\ndescription: {description}\n---\n\n# {labels[1]}\n\n'+body+'\n'
 (folder/'SKILL.md').write_text(skilltext,encoding='utf-8');(folder/'LICENSE').write_bytes((root/'LICENSE').read_bytes())
 usage=tri(('原创指令型 Skill，不附带模型、脚本或外部依赖。解压后将整个文件夹导入支持 SKILL.md 的软件；普通聊天也可粘贴 SKILL.md 和网站生成的需求。请指定回答语言。只有目标 AI 具备相应工具时才执行操作，否则交付可复制的方案。','Original instruction-only Skill. No model, scripts or external dependencies are included. Extract the folder into a SKILL.md-compatible app, or paste SKILL.md plus the website brief into chat. Specify the response language. Execute only with available host tools; otherwise deliver a copyable plan.','独自の指示文Skillです。モデル・スクリプト・外部依存は含みません。展開フォルダを対応ソフトに導入するか、SKILL.mdとサイトの要望文をチャットに貼り付け、回答言語を指定。機能がない場合は実行済みとせず利用可能な案を出します。'))
 for lang,note in usage.items(): (folder/f'USAGE.{lang}.md').write_text('# '+dict(zip(('zh','en','ja'),labels))[lang]+'\n\n'+note+'\n',encoding='utf-8')
 entry=dict(id=id,tasks=taskids,labels=tri(labels),repository='https://github.com/zhufu0801-sudo/prompt-library',source=f'https://github.com/zhufu0801-sudo/prompt-library/blob/main/data/sources/skills/{id}/SKILL.md',commit='original-v1',license='MIT',language='en',edition='original-documentation',review='package-and-scope-checked; external-ai-runtime-not-tested',usage=usage)
 entry['files']=[dict(path=p.name,sha256=hashlib.sha256(p.read_bytes()).hexdigest()) for p in sorted(folder.iterdir()) if p.is_file() and p.name!='manifest.json']
 (folder/'manifest.json').write_text(json.dumps(entry,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
 archive=root/'public/downloads/skills'/f'{id}-v1.zip'
 with zipfile.ZipFile(archive,'w',zipfile.ZIP_DEFLATED) as z:
  for p in sorted(folder.iterdir()):
   info=zipfile.ZipInfo(id+'/'+p.name,(2026,9,16,0,0,0));info.compress_type=zipfile.ZIP_DEFLATED;z.writestr(info,p.read_bytes())
 entry.update(download='/downloads/skills/'+archive.name,bytes=archive.stat().st_size,sha256=hashlib.sha256(archive.read_bytes()).hexdigest())
 skills=[s for s in skills if s['id']!=id]+[entry]
 fit[id]={'exclude':[],'scope':tri(labels),'additionalTasks':[]}
save('data/studio/skills.json',skills);save('data/studio/skill-fit.json',fit)
print('Added 12 detailed trilingual task briefs and 4 original self-contained Skill packages.')
